[meta]
entity = "MarktlokationErwDaten3"
bo4e_type = "MarktlokationErwDaten3"
companion_type = "MarktlokationErwDaten3Edifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_ze8"
discriminator = "SEQ.d1229=ZE8"

[fields]

[companion_fields]
"seq.d1229" = "seqQualifierZE8"
"rff.c506.d1153" = { target = "", default = "Z20" }
"rff.c506.d1154" = "referenzZE8"
"pia.d4347" = { target = "", default = "5" }
"pia.c212.d7140" = "obisKennzahlZE8"
"pia.c212.d7143" = { target = "", default = "Z11" }
