[meta]
entity = "ZaehlerErwDaten3"
bo4e_type = "ZaehlerErwDaten3"
companion_type = "ZaehlerErwDaten3Edifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_zf9"
discriminator = "SEQ.d1229=ZF9"

[fields]

[companion_fields]
"seq.d1229" = "seqQualifierZF9"
"seq.c286.d1050" = "zeitscheibeRefZF9"
"rff.c506.d1153" = { target = "", default = "MG" }
"rff.c506.d1154" = "referenzZF9"
