[meta]
entity = "MarktlokationErwDaten2"
bo4e_type = "MarktlokationErwDaten2"
companion_type = "MarktlokationErwDaten2Edifact"
source_group = "SG4.SG8.SG9"
source_path = "sg4.sg8_ze7.sg9"

[fields]

[companion_fields]
"qty.c186.d6060" = "jahresverbrauchsprognose"
"qty.c186.d6411" = "mengeneinheit"

"qty.c186.d6063" = { target = "", default = "11" }
