[meta]
entity = "MesslokationErwDaten"
bo4e_type = "MesslokationErwDaten"
companion_type = "MesslokationErwDatenEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_zf4.sg10"
discriminator = "CCI.d7059=Z39"

[fields]

[companion_fields]
"cci.d7059" = "cciFunktionsqualifierZ39"
"cci.c502.d6313" = "ccic502d6313Z39"
"cci.c240.d7037" = "merkmalCodeZ39"
