[meta]
entity = "Marktlokation"
bo4e_type = "Marktlokation"
source_group = "SG4.SG5"
source_path = "sg4.sg5_z16"
discriminator = "LOC.d3227=Z16"

[fields]
"loc.c517.d3225" = "marktlokationsId"
"loc.c517.d1131" = "lokationCodelisteCode"
"loc.c517.d3055" = "lokationCodepflegeCode"
"loc.c517.d3224" = "lokationZeitraumId"

"loc.d3227" = { target = "", default = "Z16" }
