[meta]
entity = "Marktteilnehmer"
bo4e_type = "Marktteilnehmer"
source_group = "SG2"
source_path = "sg2"

[fields]
"nad.d3035" = "marktrolle"
"nad.c082.d3039" = "rollencodenummer"
"nad.c082.d1131" = "codelisteCode"
"nad.c082.d3055" = "rollencodetyp"
"loc[231].d3227" = { target = "", default = "231" }
"loc[231].c517.d3225" = "regelzone"
