[meta]
entity = "Waehrung"
bo4e_type = "Waehrung"
source_group = "SG8"
source_path = "sg8"

[fields]
"cux.c504.d6347" = "waehrungsverwendung"
"cux.c504.d6345" = "waehrungCode"
"cux.c504.d6343" = "waehrungQualifier"
