[meta]
entity = "MesslokationDatenZ18"
bo4e_type = "MesslokationDatenZ18"
companion_type = "MesslokationDatenZ18Edifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_z18.sg10"
discriminator = "CCI.c240.d7037=ZB3"

[fields]

[companion_fields]
"cci.d7059" = "cciFunktionsqualifierZB3"
"cci.c502.d6313" = "ccic502d6313ZB3"
"cci.c240.d7037" = "merkmalCodeZB3"
"cav[Z91].c889.d7111" = { target = "", default = "Z91" }
"cav[Z91].c889.d1131" = "zugeordneterMpZ91"
"cav[Z91].c889.d3055" = "merkmalCodepflegeZ91"
"cav[Z91].c889.d7110" = "merkmalEigenschaftZ91"
"cav[Z91].c889.d7110_2" = "merkmalEigenschaft_2Z91"
"cav[ZF0].c889.d7111" = { target = "", default = "ZF0" }
"cav[ZF0].c889.d1131" = "zugeordneterMpZF0"
"cav[ZB4].c889.d7111" = { target = "", default = "ZB4" }
"cav[ZB4].c889.d1131" = "zugeordneterMpZB4"
