[meta]
entity = "Ansprechpartner"
bo4e_type = "Ansprechpartner"
source_group = "SG3.SG6"
source_path = "sg3.sg6_ic"

[fields]
"cta.d3139" = { target = "", default = "IC" }
"cta.c056.d3412" = "telefonnummer"
"cta.c056.d3413" = "name"
"com.c076.d3148" = "kommunikationsadresse"
"com.c076.d3155" = "kommunikationstyp"
