[meta]
entity = "SteuerbareRessourceDatenZF2"
bo4e_type = "SteuerbareRessourceDatenZF2"
companion_type = "SteuerbareRessourceDatenZF2Edifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_zf2"
discriminator = "SEQ.d1229=ZF2"

[fields]

[companion_fields]
"seq.c286.d1050" = "zeitscheibeRefZF2"
"seq.d1229" = "seqQualifierZF2"
"rff.c506.d1153" = { target = "", default = "Z38" }
"rff.c506.d1154" = "referenzZF2"
"pia.d4347" = { target = "", default = "5" }
"pia.c212.d7140" = "obisKennzahlZF2"
"pia.c212.d7143" = { target = "", default = "Z12" }
