[meta]
entity = "TechnischeRessourceErw"
bo4e_type = "TechnischeRessourceErw"
companion_type = "TechnischeRessourceErwEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_zg3.sg10"

[fields]

[companion_fields]
"cci.d7059" = { target = "", default = "Z05" }
"cav.c889.d7111" = { target = "", default = "XYZ" }
