[meta]
entity = "NetzlokationDatenZD7"
bo4e_type = "NetzlokationDatenZD7"
companion_type = "NetzlokationDatenZD7Edifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_zd7"
discriminator = "SEQ.d1229=ZD7"

[fields]
"seq.c286.d1050" = "zeitraumReferenz"

[companion_fields]
"seq.d1229" = "seqQualifierZD7"
"rff.c506.d1153" = { target = "", default = "Z32" }
"rff.c506.d1154" = "referenzZD7"
