[meta]
entity = "Referenzprofil"
bo4e_type = "Referenzprofil"
companion_type = "ReferenzprofilEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_z38.sg10"

[fields]

[companion_fields]
"cci.d7059" = { target = "", default = "Z05" }
"cav.c889.d7111" = { target = "", default = "XYZ" }
