[meta]
entity = "ZeitreihenDaten47"
bo4e_type = "ZeitreihenDaten47"
companion_type = "ZeitreihenDaten47Edifact"
source_group = "SG4.SG8.SG9"
source_path = "sg4.sg8_z47.sg9"
discriminator = "QTY.c186.d6063=Z36"

[fields]

[companion_fields]
"qty.c186.d6063" = { target = "", default = "Z36" }
"qty.c186.d6060" = "mengeZ36"
"qty.c186.d6411" = "mengeneinheitZ36"
"dtm[158].c507.d2005" = { target = "", default = "158" }
"dtm[158].c507.d2380" = "zeitpunktZ36Beginn"
"dtm[158].c507.d2379" = { target = "", default = "303" }
"dtm[159].c507.d2005" = { target = "", default = "159" }
"dtm[159].c507.d2380" = "zeitpunktZ36Ende"
"dtm[159].c507.d2379" = { target = "", default = "303" }
