[meta]
entity = "Zaehler"
bo4e_type = "Zaehler"
companion_type = "ZaehlerEdifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_z03"
discriminator = "SEQ.d1229=Z03"

[fields]

[companion_fields]
"seq.c286.d1050" = "zeitscheibeRefZ03"
"seq.d1229" = "seqQualifierZ03"
"rff[Z19].c506.d1153" = { target = "", default = "Z19" }
"rff[Z19].c506.d1154" = "referenzZ19Z03"
"rff[Z14].c506.d1153" = { target = "", default = "Z14" }
"rff[Z14].c506.d1154" = "referenzZ14Z03"
