[meta]
entity = "MengenDaten"
bo4e_type = "MengenDaten"
companion_type = "MengenDatenEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_z16.sg10"
discriminator = "CCI.c240.d7037=ZA8"

[fields]

[companion_fields]
"cci.d7059" = "cciFunktionsqualifierZA8"
"cci.c502.d6313" = "ccic502d6313ZA8"
"cci.c240.d7037" = "merkmalCodeZA8"
"cav.c889.d7111" = "merkmalQualifierZA8"
