[meta]
entity = "ObisKennzahl"
bo4e_type = "ObisKennzahl"
companion_type = "ObisKennzahlEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_z57.sg10"
discriminator = "CCI.c240.d7037=ZA7"

[fields]

[companion_fields]
"cci.d7059" = "cciFunktionsqualifierZA7z57"
"cci.c502.d6313" = "ccic502d6313ZA7z57"
"cci.c240.d7037" = "merkmalCodeZA7z57"
"cav.c889.d7111" = "merkmalQualifierZA7z57"
