[meta]
entity = "Nachricht"
bo4e_type = "Nachricht"
source_group = ""
source_path = ""

[fields]
"bgm.c002.d1001" = { target = "", default = "4" }
"bgm.c106.d1004" = "dokumentennummer"
"dtm.c507.d2005" = { target = "", default = "137" }
"dtm.c507.d2380" = "erstellungsdatum"
"dtm.c507.d2379" = { target = "", default = "303" }
