[meta]
entity = "TechRessourceErw3"
bo4e_type = "TechRessourceErw3"
companion_type = "TechRessourceErw3Edifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_zg6_zg7"
discriminator = "SEQ.d1229=ZG6"

[fields]

[companion_fields]
"seq.d1229" = "seqQualifierZG6"
"seq.c286.d1050" = "zeitscheibeRefZG6"
