[meta]
entity = "AbrechnungsDatenErw6"
bo4e_type = "AbrechnungsDatenErw6"
companion_type = "AbrechnungsDatenErw6Edifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_zb3_zb4"
discriminator = "SEQ.d1229=ZB3"

[fields]

[companion_fields]
"seq.d1229" = "seqQualifierZB3"
"seq.c286.d1050" = "zeitscheibeRefZB3"
"pia.d4347" = { target = "", default = "5" }
"pia.c212.d7140" = "obisKennzahlZB3_ZB4"
"pia.c212.d7143" = { target = "", default = "Z12" }
