[meta]
entity = "TechRessourceErw6"
bo4e_type = "TechRessourceErw6"
companion_type = "TechRessourceErw6Edifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_zh3_zh4"
discriminator = "SEQ.d1229=ZH3"

[fields]

[companion_fields]
"seq.d1229" = "seqQualifierZH3"
"seq.c286.d1050" = "zeitscheibeRefZH3"
"rff.c506.d1153" = { target = "", default = "Z14" }
"rff.c506.d1154" = "referenzZH3_ZH4"
