[meta]
entity = "TechRessourceErw3"
bo4e_type = "TechRessourceErw3"
companion_type = "TechRessourceErw3Edifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_zg6_zg7.sg10"

[fields]

[companion_fields]
"cci.d7059" = "cciFunktionsqualifier"
"cci.c502.d6313" = "ccic502_d6313"
"cci.c240.d7037" = "merkmalCodeE04"
"cav.c889.d7111" = "merkmalQualifier"
