[meta]
entity = "TrancheDaten"
bo4e_type = "TrancheDaten"
companion_type = "TrancheDatenEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_z08.sg10"
discriminator = "CCI.c240.d7037=Z12"

[fields]

[companion_fields]
"cci.d7059" = "cciFunktionsqualifierZ12"
"cci.c502.d6313" = "ccic502d6313Z12"
"cci.c240.d7037" = "merkmalCodeZ12"
"cav.c889.d7111" = { target = "", default = "XYZ" }
