[meta]
entity = "TechRessourceErw4"
bo4e_type = "TechRessourceErw4"
companion_type = "TechRessourceErw4Edifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_zg8_zg9.sg10"
discriminator = "CCI.d7059=11"

[fields]

[companion_fields]
"cci.d7059" = { target = "", default = "11" }
"cci.c502.d6313" = "ccic502d631311"
"cci.c240.d7037" = "merkmalCodeZF6"
