# Status mapping override for IFTSTA PID 21031.
#
# STS + RFF[Z13] + RFF[ACW,ADY]

[meta]
entity = "Status"
bo4e_type = "Status"
source_group = "SG14.SG15"
source_path = "sg14.sg15"

[fields]
"sts.c601.d9015" = "statusKategorie"
"sts.c555.d4405" = "statusCode"
"sts.c556.d9013" = "pruefschrittCode"
"sts.c556.d1131" = "ebdNummer"
"rff[Z13].c506.d1153" = { target = "", default = "Z13" }
"rff[Z13].c506.d1154" = "pruefidentifikator"
"rff[ACW].c506.d1153" = "acwQualifier"
"rff[ACW].c506.d1154" = "referenzVorangegangenNachricht"
"rff[ADY].c506.d1153" = "adyQualifier"
"rff[ADY].c506.d1154" = "referenzAdy"
