[meta]
entity = "Antwortkategorie"
bo4e_type = "Antwortkategorie"
source_group = "SG2"
source_path = "sg2"

[fields]
"ajt.d4465" = "antwortCode"
"ajt.d1082" = "ebdReferenz"
"ftx.d4451" = "textQualifier"
"ftx.d4453" = "textFunktion"
"ftx.c107.d4441" = "textReferenz"
"ftx.c108.d4440" = "freitext1"
"ftx.c108.d4440_2" = "freitext2"
"ftx.c108.d4440_3" = "freitext3"
"ftx.c108.d4440_4" = "freitext4"
"ftx.c108.d4440_5" = "freitext5"
