[meta]
entity = "Preis"
bo4e_type = "Preis"
source_group = "SG17.SG36.SG40"
source_path = "sg17.sg36.sg40"

[fields]
"pri.c509.d5125" = "preisQualifier"
"pri.c509.d5118" = "preisBetrag"
"pri.c509.d5375" = "preisartCode"
"pri.c509.d5387" = "preisartCode2"
"pri.c509.d5284" = "einzelpreisbasisMenge"
"pri.c509.d6411" = "masseinheit"
"dtm[163].c507.d2005" = "beginnQualifier"
"dtm[163].c507.d2380" = "beginnDatum"
"dtm[163].c507.d2379" = "beginnFormat"
"dtm[164].c507.d2005" = "endeQualifier"
"dtm[164].c507.d2380" = "endeDatum"
"dtm[164].c507.d2379" = "endeFormat"
