[meta]
entity = "AbrechnungsDatenErw7"
bo4e_type = "AbrechnungsDatenErw7"
companion_type = "AbrechnungsDatenErw7Edifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_zb5_zb6"
discriminator = "SEQ.d1229=ZB5"

[fields]

[companion_fields]
"seq.d1229" = "seqQualifierZB5"
"seq.c286.d1050" = "zeitscheibeRefZB5"
"pia.d4347" = { target = "", default = "5" }
"pia.c212.d7140" = "obisKennzahlZB5_ZB6"
"pia.c212.d7143" = { target = "", default = "Z12" }
