[meta]
entity = "Referenzprofil"
bo4e_type = "Referenzprofil"
companion_type = "ReferenzprofilEdifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_z38"
discriminator = "SEQ.d1229=Z38"

[fields]

[companion_fields]
"seq.d1229" = "seqQualifierZ38"
"seq.c286.d1050" = "zeitscheibeRefZ38"
"rff.c506.d1153" = { target = "", default = "Z18" }
"rff.c506.d1154" = "referenzZ38"
