[meta]
entity = "Vorgang"
bo4e_type = "Vorgang"
source_group = "SG27"
source_path = "sg27"

[fields]
"lin.d1082" = "positionsnummer"
"lin.d1229" = "handlungCode"
"lin.c212.d7140" = "artikelNummer"
"lin.c212.d7143" = "artikelNummerTyp"
"pia.d4347" = "piaQualifier"
"pia.c212.d7140" = "preisschluesselstamm"
"pia.c212.d7143" = "preisschluesselstammTyp"
