[meta]
entity = "VorgangZuordnung"
bo4e_type = "VorgangZuordnung"
source_group = "SG27.SG28"
source_path = "sg27.sg28"

[fields]
"cci.d7059" = "klassentyp"
"cci.c502.d6313" = "dimension"
"cci.c240.d7037" = "merkmalCode"
"cci.c240.d1131" = "merkmalCodelisteCode"
"cci.c240.d3055" = "merkmalCodepflegeCode"
"cci.c240.d7036" = "obererSchwellwert"
"cci.c240.d7036_2" = "untererSchwellwert"
