[meta]
entity = "Ansprechpartner"
bo4e_type = "Ansprechpartner"
source_group = "SG11.SG14"
source_path = "sg11.sg14_ic"

[fields]
"cta.d3139" = { target = "", default = "IC" }
"cta.c056.d3413" = "kontaktNummer"
"cta.c056.d3412" = "kontaktName"
"com.c076.d3148" = "kommunikationsadresse"
"com.c076.d3155" = "kommunikationstyp"
