[meta]
entity = "Nachricht"
bo4e_type = "Nachricht"
source_group = ""
source_path = ""

[fields]
"bgm.c002.d1001" = "dokumenttyp"
"bgm.c106.d1004" = "dokumentennummer"
"dtm[137].c507.d2005" = { target = "", default = "137" }
"dtm[137].c507.d2380" = "erstellungsdatum"
"dtm[137].c507.d2379" = { target = "", default = "303" }
"imd.d7077" = "beschreibungsformat"
"imd.c272.d7081" = "produktLeistungCode"
"ftx.d4451" = "freitextQualifier"
"ftx.d4453" = "freitextFunktion"
"ftx.c107.d4441" = "freitextCode"
"ftx.c108.d4440" = "freitext1"
"ftx.c108.d4440_2" = "freitext2"
"ftx.c108.d4440_3" = "freitext3"
"ftx.c108.d4440_4" = "freitext4"
"ftx.c108.d4440_5" = "freitext5"
"uns.d0081" = { target = "", default = "S" }
