[meta]
entity = "TechRessourceErw2"
bo4e_type = "TechRessourceErw2"
companion_type = "TechRessourceErw2Edifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_zg4_zg5.sg10"
discriminator = "CCI.d7059=Z63"

[fields]

[companion_fields]
"cci.d7059" = { target = "", default = "Z63" }
"cav.c889.d7111" = "merkmalQualifierZ63"
