[meta]
entity = "Prozessdaten"
bo4e_type = "Prozessdaten"
source_group = "SG4"
source_path = "sg4"

[fields]
"ide.d7495" = "ideQualifier"
"ide.c206.d7402" = "vorgangId"
"ftx[Z01].d4451" = { target = "", default = "Z01" }
"ftx[Z01].d4453" = "freitextQualifier"
"ftx[Z01].c107.d4441" = "freitextReferenz"
"ftx[Z01].c108.d4440" = "freitext"
"ftx[Z01].c108.d4440_2" = "freitextZeile2"
"ftx[Z01].c108.d4440_3" = "freitextZeile3"
"ftx[Z01].c108.d4440_4" = "freitextZeile4"
"ftx[Z01].c108.d4440_5" = "freitextZeile5"
