[meta]
entity = "Zaehler"
bo4e_type = "Zaehler"
companion_type = "ZaehlerEdifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_za4"
discriminator = "SEQ.d1229=ZA4"

[fields]

[companion_fields]
"seq.c286.d1050" = "zeitscheibeRefZA4"
"seq.d1229" = "seqQualifierZA4"
