[meta]
entity = "ZeitreihenDaten47"
bo4e_type = "ZeitreihenDaten47"
companion_type = "ZeitreihenDaten47Edifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_z47"
discriminator = "SEQ.d1229=Z47"

[fields]

[companion_fields]
"seq.d1229" = "seqQualifierZ47"
