[meta]
entity = "Termindaten"
bo4e_type = "Termindaten"
companion_type = "TermindatenEdifact"
source_group = "SG4.SG6"
source_path = "sg4.sg6"
discriminator = "RFF.c506.d1153=Z51|Z52"

[fields]

[companion_fields]
"rff.c506.d1153" = "termindatenQualitaet"
"rff.c506.d1154" = "termindatenReferenz"
"dtm[752].c507.d2380" = "turnusablesung"
"dtm[752].c507.d2379" = "turnusablesungFormat"

[companion_fields."dtm[752].c507.d2005"]
target = ""
default = "752"
