[meta]
entity = "Waehrung"
bo4e_type = "Waehrung"
source_group = "SG4"
source_path = "sg4"

[fields]
"cux.c504.d6347" = "waehrungQualifier"
"cux.c504.d6345" = "waehrungCode"
"cux.c504.d6343" = "waehrungTyp"
