[meta]
entity = "ZaehlwerkDaten"
bo4e_type = "ZaehlwerkDaten"
companion_type = "ZaehlwerkDatenEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_z80_z81.sg10"
discriminator = "CCI.d7059=ZA2"

[fields]

[companion_fields]
"cci.d7059" = { target = "", default = "ZA2" }
"cci.c502.d6313" = "ccic502d6313ZA2"
"cci.c240.d7037" = "merkmalCodeZA2"
