# SG9 — QTY+265 Veranschlagte Jahresmenge Gesamt/Jahresspez. Arbeit

[meta]
entity = "Marktlokation"
bo4e_type = "Marktlokation"
companion_type = "MarktlokationEdifact"
source_group = "SG4.SG8.SG9"
source_path = "sg4.sg8_z80_z81.sg9"
discriminator = "QTY.c186.d6063=265"

[fields]

[companion_fields]
"qty.c186.d6060" = "jahresspezifischeArbeit"
"qty.c186.d6411" = "jahresspezifischeArbeitEinheit"

[companion_fields."qty.c186.d6063"]
target = ""
default = "265"
