[meta]
entity = "NetznutzungsabrechnungsdatenErw"
bo4e_type = "NetznutzungsabrechnungsdatenErw"
companion_type = "NetznutzungsabrechnungsdatenErwEdifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_ze2"
discriminator = "SEQ.d1229=ZE2"

[fields]

[companion_fields]
"seq.d1229" = "seqQualifierZE2"
"rff.c506.d1153" = { target = "", default = "Z18" }
"rff.c506.d1154" = "referenzZE2"
"pia.d4347" = { target = "", default = "5" }
"pia.c212.d7140" = "obisKennzahlZE2"
"pia.c212.d7143" = { target = "", default = "Z11" }
