[meta]
entity = "RedispatchDaten"
bo4e_type = "RedispatchDaten"
companion_type = "RedispatchDatenEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_z24.sg10"
discriminator = "CCI.d7059=Z25"

[fields]

[companion_fields]
"cci.d7059" = { target = "", default = "Z25" }
"cci.c502.d6313" = "ccic502d6313Z25"
"cci.c240.d7037" = "merkmalCodeZ25"
