[meta]
entity = "Preis"
bo4e_type = "Preis"
source_group = "SG17.SG36.SG40"
source_path = "sg17.sg36.sg40"

[fields]
"pri.c509.d5125" = "preisQualifier"
"pri.c509.d5118" = "preisBetrag"
"pri.c509.d5375" = "preisartCode"
"pri.c509.d5387" = "preisartCode2"
"pri.c509.d5284" = "einzelpreisbasisMenge"
"pri.c509.d6411" = "masseinheit"
"rng.d6167" = "wertebereichQualifier"
"rng.c280.d6411" = "wertebereichMasseinheit"
"rng.c280.d6162" = "untereGrenze"
"rng.c280.d6152" = "obereGrenze"
