[meta]
entity = "Preisposition"
bo4e_type = "Preisposition"
source_group = "SG17.SG36"
source_path = "sg17.sg36"

[fields]
"lin.d1082" = "positionsnummer"
"lin.d1229" = "handlungscode"
"lin.c212.d7140" = "artikelnummer"
"lin.c212.d7143" = "artikelnummertyp"
"pia.d4347" = "piaQualifier"
"pia.c212.d7140" = "preisschluesselstamm"
"pia.c212.d7143" = "preisschluesselstammTyp"
"imd.d7077" = "beschreibungsformat"
"imd.c272.d7081" = "produktCode"
"imd.c273.d7009" = "spannungsebene"
"imd.c273.d1131" = "imdCodelisteCode"
"imd.c273.d3055" = "imdCodepflegeCode"
"imd.c273.d7008" = "produktbeschreibung"
"imd.c273.d7008_2" = "produktbeschreibung2"
