[meta]
entity = "Zaehler"
bo4e_type = "Zaehler"
companion_type = "ZaehlerEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_za4.sg10"

[fields]

[companion_fields]
"cci.d7059" = "cciFunktionsqualifier"
"cci.c502.d6313" = "ccic502_d6313"
"cci.c240.d7037" = "merkmalCodeE13"
"cav.c889.d7111" = { target = "", default = "Z30" }
"cav.c889.d1131" = "zugeordneterMp"
"cav.c889.d3055" = "merkmalCodepflege"
"cav.c889.d7110" = "merkmalEigenschaft"
"cav.c889.d7110_2" = "merkmalEigenschaft_2"
