[meta]
entity = "TechnischeRessourceErw"
bo4e_type = "TechnischeRessourceErw"
companion_type = "TechnischeRessourceErwEdifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_zg3"
discriminator = "SEQ.d1229=ZG3"

[fields]

[companion_fields]
"seq.d1229" = "seqQualifierZG3"
"seq.c286.d1050" = "zeitscheibeRefZG3"
