[meta]
entity = "Zaehler"
bo4e_type = "Zaehler"
companion_type = "ZaehlerEdifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_zf5"
discriminator = "SEQ.d1229=ZF5"

[fields]

[companion_fields]
"seq.c286.d1050" = "zeitscheibeRefZF5"
"seq.d1229" = "seqQualifierZF5"
"rff[Z19].c506.d1153" = { target = "", default = "Z19" }
"rff[Z19].c506.d1154" = "referenzZ19ZF5"
"rff[Z14].c506.d1153" = { target = "", default = "Z14" }
"rff[Z14].c506.d1154" = "referenzZ14ZF5"
