[meta]
entity = "Position"
bo4e_type = "Position"
source_group = "SG27"
source_path = "sg27"

[fields]
"lin.d1082" = "positionsnummer"
"ftx.d4451" = "textQualifier"
"ftx.d4453" = "textFunktion"
"ftx.c107.d4441" = "textReferenz"
"ftx.c108.d4440" = "freitext1"
"ftx.c108.d4440_2" = "freitext2"
