[meta]
entity = "SteuerbareRessourceDatenZ62"
bo4e_type = "SteuerbareRessourceDatenZ62"
companion_type = "SteuerbareRessourceDatenZ62Edifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_z62.sg10"

[fields]

[companion_fields]
"cci.d7059" = { target = "", default = "Z49" }
"cav.c889.d7111" = { target = "", default = "ZF2" }
"cav.c889.d1131" = "zugeordneterMp"
