[meta]
entity = "Betreiber"
bo4e_type = "Betreiber"
source_group = "SG27.SG42"
source_path = "sg27.sg42_vy"

[fields]
"nad.d3035" = { target = "", default = "VY" }
"nad.c082.d3039" = "betreiberCode"
"nad.c082.d1131" = "betreiberCodelisteCode"
"nad.c082.d3055" = "betreiberCodepflegeCode"
