[meta]
entity = "VorgangZuordnung"
bo4e_type = "VorgangZuordnung"
source_group = "SG27.SG28"
source_path = "sg27.sg28"

[fields]
"cci.d7059" = "klassentyp"
"cci.c502.d6313" = "dimension"
"cci.c240.d7037" = "merkmalCode"
"cav.c889.d7111" = "merkmalWert"
"cav.c889.d1131" = "merkmalCodelisteCode"
"cav.c889.d3055" = "merkmalCodepflegeCode"
"cav.c889.d7110" = "merkmalDatenWert"
