[meta]
entity = "VorgangReferenz"
bo4e_type = "VorgangReferenz"
source_group = "SG27.SG32"
source_path = "sg27.sg32"

[fields]
"rff.c506.d1153" = "referenzQualifier"
"rff.c506.d1154" = "referenzNummer"
"rff.c506.d1156" = "zeilennummer"
"rff.c506.d1056" = "versionsnummer"
