[meta]
entity = "Nachricht"
bo4e_type = "Nachricht"
source_group = ""
source_path = ""

[fields]
"bgm.c002.d1001" = "dokumenttyp"
"bgm.c106.d1004" = "dokumentennummer"
"bgm.d1225" = "nachrichtenfunktion"
"bgm.d4343" = "antwortart"
"bgm.d1373" = "dokumentenstatus"
"dtm[137].c507.d2005" = { target = "", default = "137" }
"dtm[137].c507.d2380" = "erstellungsdatum"
"dtm[137].c507.d2379" = { target = "", default = "303" }
"dtm[157].c507.d2005" = { target = "", default = "157" }
"dtm[157].c507.d2380" = "preisblattzeitraumEnde"
"dtm[157].c507.d2379" = { target = "", default = "303" }
"dtm[492].c507.d2005" = { target = "", default = "492" }
"dtm[492].c507.d2380" = "betrachtungszeitraum"
"dtm[492].c507.d2379" = { target = "", default = "610" }
