[meta]
entity = "Waehrung"
bo4e_type = "Waehrung"
source_group = "SG6"
source_path = "sg6"

[fields]
"cux.c504.d6347" = "waehrungsverwendung"
"cux.c504.d6345" = "waehrungCode"
"cux.c504.d6343" = "waehrungQualifier"
