[meta]
entity = "MesslokationDatenZF3"
bo4e_type = "MesslokationDatenZF3"
companion_type = "MesslokationDatenZF3Edifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_zf3"
discriminator = "SEQ.d1229=ZF3"

[fields]
"seq.c286.d1050" = "zeitraumReferenz"

[companion_fields]
"seq.d1229" = "seqQualifierZF3"
"rff.c506.d1153" = { target = "", default = "Z19" }
"rff.c506.d1154" = "referenzZF3"
