[meta]
entity = "Ansprechpartner"
bo4e_type = "Ansprechpartner"
companion_type = "AnsprechpartnerEdifact"
source_group = "SG3.SG5"
source_path = "sg3.sg5"

[fields]
"nad.c082.d3039" = "rollencodenummer"
"nad.c082.d1131" = "codelisteCode"
"nad.c082.d3055" = "rollencodetyp"

[companion_fields]
"nad.d3035" = "nadQualifier"
