[meta]
entity = "ObisKennzahlDaten"
bo4e_type = "ObisKennzahlDaten"
companion_type = "ObisKennzahlDatenEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_z17.sg10"

[fields]

[companion_fields]
"cci.d7059" = "cciFunktionsqualifier"
"cci.c502.d6313" = "ccic502_d6313"
"cci.c240.d7037" = "merkmalCodeZA8"
"cav.c889.d7111" = "merkmalQualifier"
