[meta]
entity = "SeqDatenZ33"
bo4e_type = "SeqDatenZ33"
companion_type = "SeqDatenZ33Edifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_z33"
discriminator = "SEQ.d1229=Z33"

[fields]

[companion_fields]
"seq.d1229" = "seqQualifierZ33"
