[meta]
entity = "SeqDatenZ31"
bo4e_type = "SeqDatenZ31"
companion_type = "SeqDatenZ31Edifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_z31"
discriminator = "SEQ.d1229=Z31"

[fields]

[companion_fields]
"seq.d1229" = "seqQualifierZ31"
