[meta]
entity = "MarktlokationDatenZ01"
bo4e_type = "MarktlokationDatenZ01"
companion_type = "MarktlokationDatenZ01Edifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_z01.sg10"
discriminator = "CCI.c240.d7037=ZC0|ZA6"

[fields]

[companion_fields]
"cci.d7059" = "cciFunktionsqualifierZC0"
"cci.c502.d6313" = "ccic502d6313ZC0"
"cci.c240.d7037" = "merkmalCodeZC0"
"cav.c889.d7111" = { target = "", default = "E02" }
