[meta]
entity = "Referenzprofil"
bo4e_type = "Referenzprofil"
companion_type = "ReferenzprofilEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_z38.sg10"
discriminator = "CCI.d7059=Z07"

[fields]

[companion_fields]
"cci.d7059" = { target = "", default = "Z07" }
"cci.c502.d6313" = "ccic502d6313Z07"
"cci.c240.d7037" = "merkmalCodeZ07"
