[meta]
entity = "Vorgang"
bo4e_type = "Vorgang"
source_group = "SG27"
source_path = "sg27"

[fields]
"lin.d1082" = "positionsnummer"
"lin.d1229" = "handlungCode"
"pia[5].d4347" = { target = "", default = "5" }
"pia[5].c212.d7140" = "artikelNummer"
"pia[5].c212.d7143" = "artikelNummerTyp"
"pia[Z02].d4347" = { target = "", default = "Z02" }
"pia[Z02].c212.d7140" = "zusatzArtikelNummer"
"pia[Z02].c212.d7143" = "zusatzArtikelNummerTyp"
"pia[5,1].d4347" = { target = "", default = "5" }
"pia[5,1].c212.d7140" = "obisKennzahl"
"pia[5,1].c212.d7143" = "obisKennzahlTyp"
