[meta]
entity = "Prozessdaten"
bo4e_type = "Prozessdaten"
source_group = "SG4"
source_path = "sg4"

[fields]
"ide.d7495" = "ideQualifier"
"ide.c206.d7402" = "vorgangId"
"dtm[159].c507.d2005" = { target = "", default = "159" }
"dtm[159].c507.d2380" = "aenderungBis"
"dtm[159].c507.d2379" = "aenderungBisFormat"
