[meta]
entity = "MesslokationDatenZ18"
bo4e_type = "MesslokationDatenZ18"
companion_type = "MesslokationDatenZ18Edifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_z18.sg10"
discriminator = "CCI.d7059=Z32"

[fields]

[companion_fields]
"cci.d7059" = { target = "", default = "Z32" }
"cci.c502.d6313" = "ccic502d6313Z32"
"cci.c240.d7037" = "merkmalCodeZ32"
